swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Accounts & Transactions
      summary: Récupérer toutes les transactions du mois en cours
      description: Retourne la liste des transactions groupées par compte pour le mois en cours.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          required: true
          type: string
          description: ID de la transaction à récupérer
      responses:
        200:
          description: Succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transactions'
        401:
          description: UnAuthorized
        500:
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Accounts & Transactions
      summary: Récupérer les détails d'une transaction
      description: Retourne les détails d'une transaction spécifique.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID de la transaction à récupérer
        - name: accountId
          in: path
          required: true
          type: string
          description: ID de la transaction à récupérer
      responses:
        200:
          description: Succès
          schema:
            $ref: '#/definitions/Transaction'
        401:
          description: UnAuthorized
        500:
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - User Accounts & Transactions
      summary: Mettre à jour une transaction
      description: Met à jour les informations d'une transaction spécifique.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID de la transaction à mettre à jour
        - name: accountId
          in: path
          required: true
          type: string
          description: ID de la transaction à récupérer
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TransactionInput'
      responses:
        204:
          description: Succès
        401:
          description: UnAuthorized
        500:
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: object
    properties:
      transactionId:
        type: string
      description:
        type: string
      amount:
        type: number
      date:
        type: string
      balance:
        type: number

  Transaction:
    type: object
    properties:
      transactionId:
        type: string
      description:
        type: string
      amount:
        type: number
      date:
        type: string
      balance:
        type: number
      transactionType:
        type: string
      category:
        type: string
      note:
        type: string
  TransactionInput:
    type: object
    properties:
      category:
        type: string
      note:
        type: string